name: Python Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.1
    - name: Install PIP dependencies
      run: |
        pip3.9 install -r requriments.txt
    - name: Test with unittest
      run: |
        python3.9 -m unittest discover -s . -p "*_test.py" -v
